### ISSUE TITLE
Links in the about page are 404ing

### ISSUE THREAD

**Issue by codersquid** [accountability-guides/accountability-guides.github.io#1]
The navbar links work, but the links in the page return 404s.

**Comment by neverett** [comment]
Good catch, fixed in https://github.com/accountability-guides/accountability-guides.github.io/commit/27f0f11fab14262caa9d6c1be16bd9f41aff08d1

**Comment by neverett** [comment]
Links are working for me now, but let me know if anything else looks broken.
